# Do not change version. This is the version of aws buildspec, not the version of your buildspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing Surge...
      - npm install -g surge
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install ra-data-json-server
      - npm install -i
  build:
    commands:
      - echo Build started
      - echo Compiling the Node.js code
      - CI=false npm run build
  post_build:
    commands:
      - echo Build completed
      - aws s3 rm s3://devops-ltpl/ --recursive 
      - aws s3 cp build s3://devops-ltpl/ --recursive
    #   - aws s3 sync build s3://<bucketname>/ --recursive

# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
