name: Production Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.16.2]
        
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Basic Package Install
      run: |
        npm install ra-data-json-server
    - name: NPM Install
      run: |
       npm install
    - name: Build Creation
      run: |
       CI=false npm run build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    - name: Cleaning S3 bucket with the AWS CLI
      run: |
       aws s3 rm s3://bucket-name/ --recursive        
    - name: Copy build to S3 bucket with the AWS CLI
      run: |
       aws s3 cp build/ s3://bucket-name/ --recursive 
